config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: %i[new create destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: {
    in: %w[chinese italian japanese french belgian],
    message: 'This is not a valid category'
  }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, presence: true, numericality: { only_integer: true }, inclusion: {
    in: (0..5),
    message: 'This is not a valid rating'
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[show edit update destroy]
  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: %i[destroy]

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    @review.save
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def destroy
    @review.destroy
    redirect_to reviews_path
  end

  private

  def set_review
    @review = review.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :category %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>

app/views/restaurants/edit.html.erb
<div class="container">
  <h1>Edit a Restaurant:</h1>
  <div class="form">
    <%= render "form", restaurant: @restaurant %>
  </div>
  <span id="back"><%= link_to("Back to list", restaurants_path) %></span>
</div>

app/views/restaurants/index.html.erb
<div class="container">
  <h1>Restaurants List:</h1>

  <% @restaurants.each do |restaurant| %>
    <div class="restaurant-display">
      <p class = "restaurant-name">
        <%= link_to(restaurant.name, restaurant_path(restaurant)) %>
      </p>
      <p class = "restaurant-infos">
        <%= restaurant.address %>
        <%= restaurant.category %>
      <p class = "restaurant-infos">
    </div>
  <% end %>

  <p class="buttons" id= "newrestaurant"><%= link_to("+ Add a new restaurant", new_restaurant_path) %></p>
</div>

app/views/restaurants/new.html.erb
<div class="container">
  <h1>Create a restaurant:</h1>
  <div class="form">
    <%= render "form", restaurant: @restaurant %>
  </div>
  <div class=buttons>
  <span id="back"><%= link_to("Back to list", restaurants_path) %></span>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <h1><%= @restaurant.name %></h1>
  <div class="description">
    <h3><%= @restaurant.category %></h3>
    <h3><%= @restaurant.address %></h3>
    <h3><%= @restaurant.phone_number %></h3>
  </div>
  <div class="reviews">
    <ul class="list-group">
    <h2>Reviews</h2>
    <%= link_to("Write a review", new_restaurant_review_path(@restaurant)) %>
    <% @restaurant.reviews.each do |review| %>
      <li class="review"><%= review.content %></li>
    <% end %>
    </ul>
  </div>

  <div class="buttons">
    <span id="edit"><%= link_to("Edit this restaurant", edit_restaurant_path) %></span>
    <span id="delete"><%= link_to "Delete #{@restaurant.name}",
                restaurant_path(@restaurant),
                method: :delete,
                data: { confirm: "Are you sure?" } %></span>
    <span id="back"><%= link_to("Back to Restaurants", restaurants_path) %></span>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="container">
  <h1>Write a review about the restaurant:</h1>
  <div class="review-form">
    <%= simple_form_for([@restaurant, @review]) do |f| %>
      <%= f.input :rating %>
      <%= f.input :content %>
      <%= f.submit "Submit review", class: "btn btn-primary" %>
    <% end %>
  </div>
  <span class="buttons" id="back"><%= link_to("Back to list", restaurants_path) %></span>
</div>